#!/usr/bin/env bash
set -Eeuo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

OUTPUT_FILE="$PROJECT_DIR/config/model-stats.conf"
REPORT_DIR="$PROJECT_DIR/reports"
mkdir -p "$REPORT_DIR"
REPORT_FILE="$REPORT_DIR/model-measurement-$(date +%F_%H-%M-%S).txt"

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

# Globals for aggregation
TOTAL_FACTOR=0
TOTAL_OVERHEAD=0
COUNT=0
CONTAINERS=()

MODEL_CONFIG="$PROJECT_DIR/config/enabled-models.conf"

ENABLED_MODELS=()
ENABLED_LINES=()

#tmp
TMP_DIR=""
TMP_CONFIG=""

# new function

load_enabled_models() {

    ENABLED_MODELS=()

    local LINE_NO=0

    while IFS= read -r LINE; do

        ((++LINE_NO))

        [[ -z "$LINE" || "$LINE" =~ ^# ]] && continue

        local TYPE
        local CFG_MODEL
        local STATE
        local PRIORITY
        local TP
        local DEVICE
        local VRAM

        IFS='|' read -r \
            TYPE \
            CFG_MODEL \
            STATE \
            PRIORITY \
            TP \
            DEVICE \
            VRAM <<< "$LINE"

        [[ "$STATE" != "on" ]] && continue

        ENABLED_MODELS+=("${LINE_NO}|${CFG_MODEL}")

    done < "$MODEL_CONFIG"
}

# new function build_temp_config
build_temp_config() {

    local ACTIVE_LINE="$1"
    local ACTIVE_MODEL="$2"

    local LINE_NO=0

    TMP_CONFIG="$(mktemp)"
    TMP_COMPOSE_DIR="$(mktemp -d)"
    local FOUND=0

    TMP_CONFIG="$(mktemp)"
    TMP_COMPOSE_DIR="$(mktemp -d)"

    while IFS= read -r LINE; do
        ((++LINE_NO))

        # comments / empty lines
        if [[ -z "$LINE" || "$LINE" =~ ^# ]]; then
            echo "$LINE" >> "$TMP_CONFIG"
            continue
        fi

        local TYPE
        local CFG_MODEL
        local STATE
        local PRIORITY
        local TP
        local DEVICE
        local VRAM

        IFS='|' read -r \
            TYPE \
            CFG_MODEL \
            STATE \
            PRIORITY \
            TP \
            DEVICE \
            VRAM <<< "$LINE"

        if (( LINE_NO == ACTIVE_LINE )); then
            STATE="on"
        else
            STATE="off"
        fi

        printf "%s|%s|%s|%s|%s|%s|%s\n" \
            "$TYPE" \
            "$CFG_MODEL" \
            "$STATE" \
            "$PRIORITY" \
            "$TP" \
            "$DEVICE" \
            "$VRAM" \
            >> "$TMP_CONFIG"

    done < "$MODEL_CONFIG"

    echo
    echo "=========================================="
    echo "Temporary config for: $ACTIVE_MODEL"
    echo "=========================================="
    cat "$TMP_CONFIG"
}


print_header() {
    cat > "$OUTPUT_FILE" <<EOF
# ==========================================================
# AUTO GENERATED
# Generated by scripts/measure-models.sh
# ==========================================================
#
# model|scheduler_memory_gb|gpu|weight_gb|total_vram_gb|overhead_gb|memory_factor|max_context|dtype|tensor_parallel|container_uptime_sec|vllm_version|driver|cuda|date
#
EOF

    exec > >(tee "$REPORT_FILE")
    echo "=============================================================="
    echo "AI Platform Model Measurement"
    echo "=============================================================="
}

find_containers() {
    # More robust detection: match image name prefix so tags don't break it
    mapfile -t CONTAINERS < <(
        docker ps --format '{{.Names}} {{.Image}}' \
        | awk '$2 ~ /^vllm\/vllm-openai/ {print $1}'
    )

    if [[ ${#CONTAINERS[@]} -eq 0 ]]; then
        echo "No running vLLM containers found."
        exit 1
    fi
}

# Safe helpers to extract from docker inspect Cmd array
extract_cmd_value_after_flag() {
    # $1 = container, $2 = flag (e.g. --served-model-name or --model)
    local container="$1"
    local flag="$2"
    docker inspect "$container" \
        | jq -r '.[0].Config.Cmd[]' \
        | awk -v f="$flag" '
            # handle "--flag=value"
            $0 ~ f"=" {
                split($0, a, "=");
                print a[2];
                exit
            }
            # handle "--flag" followed by value on next line
            prev==f {
                print $0;
                exit
            }
            { prev=$0 }
        '
}

# Safe log parsing using awk to avoid grep exit codes
extract_context_from_logs() {
    local container="$1"
    docker logs "$container" 2>&1 \
    | awk '/Using max model len/{
        for(i=1;i<=NF;i++){
            if($i ~ /^[0-9]+$/){print $i; exit}
        }
    }' || true
}

extract_dtype_from_logs() {
    local container="$1"
    docker logs "$container" 2>&1 \
    | awk '{
        for(i=1;i<=NF;i++){
            if($i ~ /dtype=/){
                sub(/.*dtype=/,"",$i);
                gsub(/[,:]/,"",$i);
                print $i;
                exit
            }
        }
    }' || true
}

extract_tp_from_logs() {
    local container="$1"
    docker logs "$container" 2>&1 \
    | awk '{
        for(i=1;i<=NF;i++){
            if($i ~ /tensor_parallel_size=/){
                sub(/.*tensor_parallel_size=/,"",$i);
                gsub(/[,:]/,"",$i);
                print $i;
                exit
            }
        }
    }' || true
}

# Write a single stats line to OUTPUT_FILE (with scheduler_memory_gb as second column)
write_stats() {
    local model="$1"
    local scheduler_memory_gb="$2"
    local gpu="$3"
    local weight="$4"
    local total_vram="$5"
    local overhead="$6"
    local factor="$7"
    local context="$8"
    local dtype="$9"
    local tp="${10}"
    local container_uptime="${11}"
    local vllm="${12}"
    local driver="${13}"
    local cuda="${14}"
    local date_str="${15}"

    echo "${model}|${scheduler_memory_gb}|${gpu}|${weight}|${total_vram}|${overhead}|${factor}|${context}|${dtype}|${tp}|${container_uptime}|${vllm}|${driver}|${cuda}|${date_str}" \
        >> "$OUTPUT_FILE"
}

measure_container() {
    local CONTAINER="$1"

    # Localize all variables used in this function to avoid global pollution
    local MODEL
    local MODEL_PATH
    local WEIGHT
    local GPU
    local TOTAL_VRAM
    local SCHEDULER_MEMORY_GB
    local OVERHEAD
    local FACTOR
    local CONTEXT
    local DTYPE
    local TP
    local CREATED
    local START
    local NOW
    local CONTAINER_UPTIME
    local VLLM
    local DRIVER
    local CUDA

    echo
    echo "--------------------------------------------------------------"

    # Model name (handles both --served-model-name=value and --served-model-name <value>)
    MODEL=$(extract_cmd_value_after_flag "$CONTAINER" "--served-model-name")
    [[ -z "$MODEL" ]] && MODEL="$CONTAINER"

    # Model path (handles --model <path>)
    MODEL_PATH=$(extract_cmd_value_after_flag "$CONTAINER" "--model" || true)

    # Weight (size) - be robust if MODEL_PATH empty or du fails; suppress warnings
    WEIGHT=""
    if [[ -n "$MODEL_PATH" ]]; then
        WEIGHT=$(docker exec "$CONTAINER" \
            sh -c "if [ -e '$MODEL_PATH' ]; then du -sb '$MODEL_PATH' 2>/dev/null; fi" \
            | awk '{ if ($1) printf "%.2f", $1/1024/1024/1024; else print "" }')
    fi

    # If WEIGHT empty, set to 0.00
    if [[ -z "$WEIGHT" ]]; then
        WEIGHT="0.00"
    fi

    # GPU
    GPU=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || true)
    GPU=${GPU:-"unknown"}

    # TOTAL_VRAM (GB) - sum of used_gpu_memory (kB -> MB -> GB)
    TOTAL_VRAM=$(nvidia-smi --query-compute-apps=used_gpu_memory --format=csv,noheader,nounits 2>/dev/null \
        | awk '{s+=$1} END{ if(s) printf "%.2f", s/1024; else print "0.00"}' || echo "0.00")

    # scheduler_memory_gb: new column, for now equal to total_vram
    SCHEDULER_MEMORY_GB="${TOTAL_VRAM}"
    # TODO:
    # In benchmark mode (one model per GPU),
    # scheduler_memory_gb == total_vram_gb.
    # In future versions this value may come from
    # measured dedicated memory.

    # Overhead and Factor (guard division by zero)
    if [[ -z "$WEIGHT" || "$WEIGHT" == "0.00" || "$WEIGHT" == "0" ]]; then
        OVERHEAD="0.00"
        FACTOR="0.00"
    else
        OVERHEAD=$(awk -v a="$TOTAL_VRAM" -v b="$WEIGHT" 'BEGIN{printf "%.2f", a-b}')
        FACTOR=$(awk -v a="$TOTAL_VRAM" -v b="$WEIGHT" 'BEGIN{ if(b==0){print "0.00"} else printf "%.2f", a/b }')
    fi

    # Context, dtype, tp (safe parsing)
    CONTEXT=$(extract_context_from_logs "$CONTAINER")
    DTYPE=$(extract_dtype_from_logs "$CONTAINER")
    # Normalize dtype
    DTYPE=${DTYPE#torch.}

    case "$DTYPE" in
        bfloat16) DTYPE="bf16" ;;
        float16)  DTYPE="fp16" ;;
        float32)  DTYPE="fp32" ;;
    esac
       
    TP=$(extract_tp_from_logs "$CONTAINER")

    # Container uptime (previously called STARTUP)
    CREATED=$(docker inspect --format '{{.Created}}' "$CONTAINER")
    START=$(date -d "$CREATED" +%s)
    NOW=$(date +%s)
    CONTAINER_UPTIME=$((NOW-START))

    # vLLM version (guard errors)
    VLLM=$(docker exec "$CONTAINER" python3 -c "import vllm;print(vllm.__version__)" 2>/dev/null || echo "unknown")

    # Driver / CUDA
    DRIVER=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null | head -1 || true)
    DRIVER=${DRIVER:-"unknown"}

    CUDA=$(nvidia-smi 2>/dev/null | grep -m1 "CUDA Version" | sed 's/.*CUDA Version: //' | awk '{print $1}' || true)
    CUDA=${CUDA:-"unknown"}

    # Report to stdout
    printf "Model              : %s\n" "$MODEL"
    printf "GPU                : %s\n" "$GPU"
    printf "Weight             : %s GB\n" "$WEIGHT"
    printf "VRAM               : %s GB\n" "$TOTAL_VRAM"
    printf "Scheduler Memory   : %s GB\n" "$SCHEDULER_MEMORY_GB"
    printf "Overhead           : %s GB\n" "$OVERHEAD"
    printf "Memory Factor      : %s\n" "$FACTOR"
    printf "Context            : %s\n" "${CONTEXT:-unknown}"
    printf "dtype              : %s\n" "${DTYPE:-unknown}"
    printf "Tensor Parallel    : %s\n" "${TP:-unknown}"
    printf "Container Uptime   : %s sec\n" "$CONTAINER_UPTIME"
    printf "vLLM               : %s\n" "$VLLM"
    echo

    # Append to OUTPUT_FILE via write_stats (scheduler_memory_gb is second column)
    write_stats \
        "$MODEL" \
        "$SCHEDULER_MEMORY_GB" \
        "$GPU" \
        "$WEIGHT" \
        "$TOTAL_VRAM" \
        "$OVERHEAD" \
        "$FACTOR" \
        "${CONTEXT:-}" \
        "${DTYPE:-}" \
        "${TP:-}" \
        "$CONTAINER_UPTIME" \
        "$VLLM" \
        "$DRIVER" \
        "$CUDA" \
        "$(date +%F)"

    # Aggregate safely (use awk to sum floats)
    TOTAL_FACTOR=$(awk -v a="$TOTAL_FACTOR" -v b="$FACTOR" 'BEGIN{printf "%.6f", a+b}')
    TOTAL_OVERHEAD=$(awk -v a="$TOTAL_OVERHEAD" -v b="$OVERHEAD" 'BEGIN{printf "%.6f", a+b}')

    ((COUNT++))
}

print_summary() {
    echo "=============================================================="
    if (( COUNT > 0 )); then
        AVG_FACTOR=$(awk -v a="$TOTAL_FACTOR" -v c="$COUNT" 'BEGIN{printf "%.2f", a/c}')
        AVG_OVERHEAD=$(awk -v a="$TOTAL_OVERHEAD" -v c="$COUNT" 'BEGIN{printf "%.2f", a/c}')
    else
        AVG_FACTOR="0.00"
        AVG_OVERHEAD="0.00"
    fi
    printf "Average Memory Factor : %s\n" "$AVG_FACTOR"
    printf "Average Overhead      : %s GB\n" "$AVG_OVERHEAD"
    echo "=============================================================="

    echo
    echo "Statistics written to:"
    echo "$OUTPUT_FILE"

    echo
    echo "Report written to:"
    echo "$REPORT_FILE"
}

# new function - cleanup_temp
#cleanup_temp() {

#    [[ -n "${TMP_CONFIG:-}" ]] && rm -f "$TMP_CONFIG"
#    [[ -n "${TMP_COMPOSE_DIR:-}" ]] && rm -rf "$TMP_COMPOSE_DIR"

#    unset TMP_CONFIG
#    unset TMP_COMPOSE_DIR
#}

main() {
    print_header

    load_enabled_models

    echo "Loaded ${#ENABLED_MODELS[@]} models"

    for ENTRY in "${ENABLED_MODELS[@]}"; do

        IFS='|' read -r ACTIVE_LINE ACTIVE_MODEL <<< "$ENTRY"

        build_temp_config "$ACTIVE_LINE" "$ACTIVE_MODEL"

        echo
        echo "Registering model..."
        "$PROJECT_DIR/scripts/register-models.sh" \
            --config "$TMP_CONFIG" \
            --output-dir "$TMP_COMPOSE_DIR"

        echo
        echo "Starting platform..."
        "$PROJECT_DIR/scripts/start-ai-platform.sh" \
            --compose-dir "$TMP_COMPOSE_DIR"

        echo
        echo "Waiting for containers to become healthy..."
        "$PROJECT_DIR/scripts/wait-healthy.sh" \
            --compose-dir "$TMP_COMPOSE_DIR"

        echo
        echo "Generated files:"
        find "$TMP_COMPOSE_DIR" -maxdepth 1 -type f | sort

        # مراحل بعدی:
        # find_containers
        # measure_container
        # stop-ai-platform.sh --compose-dir "$TMP_COMPOSE_DIR"
        # cleanup_temp

    done
}

main "$@"
